# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A straightforward Jekyll theme (built by @mdo, hosted on teddyhyde.io)'
url:              http://hyde.teddyhyde.io
baseurl:          /

author:
  name:           'Teddy Hyde'
  url:            https://twitter.com/xrd

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tedhyde/hyde
